language: node_js
node_js:
  - node
dist: trusty
addons:
  apt:
    packages:
    - libcairo2-dev
    - libjpeg-dev
    - libpango1.0-dev
    - libgif-dev
    - build-essential
    - g++
    - libnss3
cache:
  directories:
    - node_modules
# allow headful tests
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - node index.js web &
  - node index.js worker &
  - npm test
