#/bin/sh
# I AM NOT RESPONSIBLE FOR ANY DAMAGE THIS COMMAND DOES
# YOU SHOULDN'T BE USING THE TEST DATABASE IN PRODUCTION IN THE FIRST PLACE
# NOR SHOULD YOU BE RUNNING RANDOM SCRIPTS WITHOUT UNDERSTANDING WHAT THEY DO
mongo test --eval "db.dropDatabase()"
